
# 无人机巡航任务参数配置
# --------- 控制参数 (可以根据实际情况调整) ---------
# 位置控制容忍度 (单位: 米)
# 到达目标点的判断阈值，越小越精确，但可能会导致无人机在目标点附近震荡
position_tolerance: 0.2
err_max: 0.2

# 最大偏航角速度 (单位: 弧度/秒)
# 控制无人机旋转的速度，值越大转得越快
max_yaw_rate: 1.5

# 主循环控制频率 (单位: Hz)
# 控制指令的发送频率，建议与飞控的期望频率匹配 (例如 20-50Hz)
control_rate: 20.0


# --------- 模式切换 ---------
# 是否自动切换到 OFFBOARD 模式
# true: 程序会自动调用服务切换模式
# false: 程序会等待你从地面站或遥控器手动切换到 OFFBOARD 模式
auto_offboard: true

num_checkpoints: 1

checkpoints:
  "0":
    x: 1.0
    y: 0.0
    z: 1.0
    yaw: 0.0
